name: Deploy Slides

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  deploy-slides:
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/slides/Gemfile
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/ruby/jekyll@v0
        with:
          docs-directory: slides
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ruby-version: "3.2"
